### ISSUE TITLE
Run a job immediately, and then hourly after that

### ISSUE THREAD

**Issue by rarkins** [citusdata/pg_cron#184]
When creating a new hourly cron I would like to configure that it runs "immediately" (ideally within a minute) and then hourly after that. Is there any way to do this without needing to worry about race conditions (e.g. next minute ticks over in the instant before pg_cron checks). One possibility might be to set it to be *2* minutes after current time, but even still I am concerned about clock drift between the client creating the scheduled entry vs Postgres itself.

**Comment by phuochau** [comment]
I have the same question, we would like to run a HTTP request instantly after adding the cron job and repeat X minutes later then but not sure how to achieve that. @rarkins did you solve your problem?

**Comment by rarkins** [comment]
@phuochau I was not able to solve this in the way I asked above. We added a wrapper to check how long since the last time it was run and skip if it was <1 hour. So that way we get the first one, but then the second one could in theory be up to 1:00-1:59 later, and then after that it's hourly

**Comment by phuochau** [comment]
@rarkins I can solve the issue by doing a trick. Because my cron job will call another Postgres function. In another Postgres function, it provides a param to let us know that we need to reschedule the job.

So the first time, I schedule the cron job for the next minute '* * * * *', and after executing the function, I reschedule to every hour. It works well now for my problem.
