### ISSUE TITLE
confirmation that pg_cron only runs on one database per server

### ISSUE THREAD

**Issue by chrislungu** [citusdata/pg_cron#334]
hi all,

I just want to confirm something, the documentation is not best (sorry). it says the following:

> pg_cron may only be installed to one database in a cluster. If you need to run jobs in multiple databases, use cron.schedule_in_database().

may I confirm that this means, in practice, that if I install pg_cron in the database "postgres" and I have additional databases on the same server, I can use pg_cron to schedule jobs across the entire server, i.e. in other databases?

thank you

**Comment by AyoubKaz07** [comment]
Kinda late, but it seems clear
However, if you want to run a cron job across multiple databases you would use `cron.schedule_in_database()` instead of `cron.schedule()`.

`cron.schedule_in_database()` just has an extra param, which is the database name where the job should run.

Example from the docs:
> https://github.com/citusdata/pg_cron/blob/f5d111117ddc0f4d83a1bad34d61b857681b6720/README.md?plain=1#L40

**Comment by chrislungu** [comment]
thanks, it's clear!
