### ISSUE TITLE
Can't dump pg_cron schema

### ISSUE THREAD

**Issue by ykurenkov** [citusdata/pg_cron#81]
PostgreSQL 10 from PGDG, Ubuntu 18.10:

Check PG config:
```
postgres@pg_probackup:~$ grep cron /etc/postgresql/10/main/conf.d/local.conf
shared_preload_libraries = 'pg_cron'
cron.database_name = 'postgres'

```
Show jobs:
```
postgres@pg_probackup:~$ psql -U postgres -c '\x' -c 'select * from cron.job'
Expanded display is on.
-[ RECORD 1 ]----------------------------------------------
jobid    | 2
schedule | */1 * * * *
command  | insert into testdata (testdata) values ('cron');
nodename | localhost
nodeport | 5432
database | testdb
username | postgres
active   | t

```
And now dump DB postgres
```
postgres@pg_probackup:~$ pg_dump -U postgres -f postgres.sql

```
Result in attach. What is wrong?
[postgres.sql.gz](https://github.com/citusdata/pg_cron/files/3550403/postgres.sql.gz)

**Comment by ykurenkov** [comment]
Hm... May be I can help. https://www.postgresql.org/docs/10/extend-extensions.html#EXTEND-EXTENSIONS-CONFIG-TABLES

**Comment by ykurenkov** [comment]
What do you think about this?

```
--- pg_cron--1.1.sql.orig       2019-04-10 13:01:26.000000000 +0000
+++ pg_cron--1.1.sql    2019-08-29 05:49:23.632854920 +0000
@@ -28,6 +28,9 @@
 ALTER TABLE cron.job ENABLE ROW LEVEL SECURITY;
 CREATE POLICY cron_job_policy ON cron.job USING (username = current_user);

+SELECT pg_catalog.pg_extension_config_dump('cron.job', '');
+SELECT pg_catalog.pg_extension_config_dump('cron.Jobid_seq', '');
+
 CREATE FUNCTION cron.schedule(schedule text, command text)
     RETURNS bigint
     LANGUAGE C STRICT
```
```
# grep -A 5 -B 2 COPY postgres.sql
--

COPY cron.job (jobid, schedule, command, nodename, nodeport, database, username, active) FROM stdin;
1       */1 * * * *     insert into testdata (testdata) values ('cron');        localhost       5432    testdb  postgres t
\.


--
```
After inserting call SELECT pg_catalog.pg_extension_config_dump('my_config', ''); I can dump my pg_cron jobs!

**Comment by keithf4** [comment]
Yes, that is a setting you can do for extension tables. But be aware that this causes that data to always be dumped no matter what, even in a schema only dump. So should only ever be used with tables that have a generally small amount of data. It's intention was for dumping out small config tables, which these may qualify as.

**Comment by pluzanov** [comment]
What you mean by _data to always be dumped no matter what, even in a schema only dump_ ?
```pg_dump -s``` will never dump data inserted after creation of extension.
I think that adding these two lines
```
SELECT pg_catalog.pg_extension_config_dump('cron.job');
SELECT pg_catalog.pg_extension_config_dump('cron.jobid_seq');
```
 in a new version (1.2) of extension is a safe and allows to make copy (by pg_dump) of cron jobs.
If you agree, I can send a pull request?

**Comment by keithf4** [comment]
Guess they must have fixed that but never documented it that I can see, so not sure what version it was fixed in. I remember it used to be a big issue because I had a problem with the data in a large extension table always getting dumped out in my pg_jobmon extension, even in schema only dumps (https://github.com/keithf4/pg_jobmon). So I'd still be careful.

Still, check the docs on what the intention of that setting is.
```
To solve this problem, an extension's script file can mark a table or a sequence it has created as a configuration relation, which will cause pg_dump to include the table's or the sequence's contents (not its definition) in dumps
``` 
https://www.postgresql.org/docs/11/extend-extensions.html#EXTEND-EXTENSIONS-CONFIG-TABLES

So you're still not dumping the table's schema out, only flagging that its data needs to be dumped. The table schema is still handled by the CREATE EXTENSION statement. Also FYI, you'll only get that statement when you dump the whole database, not just the schema your extension lives in or other smaller parts of the database. 

I'm sure you're free to do a PR, but I'm not a maintainer on this project, just a user.

**Comment by marcocitus** [comment]
Thanks for pointing this out. There was a bug in the Makefile which caused the `pg_extension_config_dump` call to be skipped. Fixed this on the master branch by adding a new upgrade script.

**Comment by pluzanov** [comment]
Marco, thank you for quick response!

**Comment by ykurenkov** [comment]
Thanks to all!
