### ISSUE TITLE
pg_cron background worker does not work

### ISSUE THREAD

**Issue by bagafoot** [citusdata/pg_cron#99]
I'm using pg12.1 version and installed pg_cron_12.
I'm created extention set cron.database_name and insert into cron.job.
Firs days it was working well but today I realised pg_cron background worker does not work and all my scheduled jobs.
How can I resart pg_cron bgw.

**Comment by koktan** [comment]
Hello, is there a solution to this? I have the same problem, pg_cron stoped working, in the log is only message:
LOG:  pg_cron scheduler shutting down
I cann't find a way how to start it (i guess restart the whole database would work but that's not what i can do just anytime)
Thanks

**Comment by marcocitus** [comment]
If you use pg_terminate_backend on the pg_cron process (or send a SIGTERM) it will go away and not come back until you restart PostgreSQL.

**Comment by davidradernj** [comment]
We set a [restart_time = 1](https://github.com/citusdata/pg_cron/blob/4da3981fea8688518e7cde39b685cc0a37903f9c/src/pg_cron.c#L320)
But, we [proc_exit(0)](https://github.com/citusdata/pg_cron/blob/4da3981fea8688518e7cde39b685cc0a37903f9c/src/pg_cron.c#L653)

According to PG [docs](https://www.postgresql.org/docs/current/bgworker.html), "If bgw_restart_time for a background worker is configured as BGW_NEVER_RESTART, or if it exits with an exit code of 0 or is terminated by TerminateBackgroundWorker, it will be automatically unregistered by the postmaster on exit. Otherwise, it will be restarted after the time period configured via bgw_restart_time, or immediately if the postmaster reinitializes the cluster due to a backend failure."
